apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-bootstrap
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bootstraping elements for {{ .Values.environment }} kubernetes cluster
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'